### ISSUE TITLE
Build fails on Fedora Linux

### ISSUE THREAD

**Issue by stevenroose** [Open-Transactions/opentxs-proto#1]
I got this error message from `cmake`:
```
$ cmake ..
-- C++ Compiler ID: GNU
-- C++ Flags:        -std=c++11 -pthread -fPIC
-- C++ link flags:  
-- Package version:  0.0.0
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PROTOBUF_LITE_LIBRARY (ADVANCED)
    linked by target "opentxs-proto" in directory /home/steven/git/opentxs-proto/src/proto

-- Configuring incomplete, errors occurred!
See also "/home/steven/git/opentxs-proto/build/CMakeFiles/CMakeOutput.log".
See also "/home/steven/git/opentxs-proto/build/CMakeFiles/CMakeError.log".
```

These are the two mentioned files: 
https://gist.github.com/stevenroose/c3a7679510d1db17c3a7

And these are the protobuf-related packages I got installed:
![](https://i.imgur.com/WFmI3Qp.png)

**Comment by stevenroose** [comment]
bump

**Comment by justusranvier** [comment]
You need protobuf 2.6 or greater.

If that version is not available for F22, you might need to compile and install it manually.

**Comment by stevenroose** [comment]
Fixed by https://github.com/Open-Transactions/opentxs-proto/commit/3e46304f2c9304ee1edea298070e64e18a877f8c
